/*
 * Kaia Mac
 * This program is a quiz all about codes, it will test you and calculate your score
 * October 12, 2018
 */

/**
 *
 * @author kaiat
 */
public class FormSummativeProject extends javax.swing.JFrame {

    /**
     * Creates new form FormSummativeProject
     */
    public FormSummativeProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        pictureLabel = new javax.swing.JLabel();
        informationBackgroundPanel = new javax.swing.JPanel();
        quizInstructionsLabel2 = new javax.swing.JLabel();
        quizInstructionsLabel3 = new javax.swing.JLabel();
        quizInstructionsLabel1 = new javax.swing.JLabel();
        label1Question1 = new javax.swing.JLabel();
        label2Question1 = new javax.swing.JLabel();
        panelCodeQuestion1 = new javax.swing.JPanel();
        line1Question1 = new javax.swing.JLabel();
        line2Question1 = new javax.swing.JLabel();
        line3Question1 = new javax.swing.JLabel();
        line4Question1 = new javax.swing.JLabel();
        line5Question1 = new javax.swing.JLabel();
        line6Question1 = new javax.swing.JLabel();
        labelAnswer1Question1 = new javax.swing.JLabel();
        labelAnswer2Question1 = new javax.swing.JLabel();
        labelAnswer3Question1 = new javax.swing.JLabel();
        labelAnswer4Question1 = new javax.swing.JLabel();
        userInputQuestion1 = new javax.swing.JTextField();
        label1Question2 = new javax.swing.JLabel();
        label2Question2 = new javax.swing.JLabel();
        panelCodeQuestion2 = new javax.swing.JPanel();
        line1Question2 = new javax.swing.JLabel();
        line2Question2 = new javax.swing.JLabel();
        line3Question2 = new javax.swing.JLabel();
        line4Question2 = new javax.swing.JLabel();
        labelAnswer1Question2 = new javax.swing.JLabel();
        labelAnswer2Question2 = new javax.swing.JLabel();
        labelAnswer3Question2 = new javax.swing.JLabel();
        labelAnswer4Question2 = new javax.swing.JLabel();
        userInputQuestion2 = new javax.swing.JTextField();
        label1Question3 = new javax.swing.JLabel();
        label2Question3 = new javax.swing.JLabel();
        panelCodeQuestion3 = new javax.swing.JPanel();
        line1Question3 = new javax.swing.JLabel();
        line2Question3 = new javax.swing.JLabel();
        line3Question3 = new javax.swing.JLabel();
        line4Question3 = new javax.swing.JLabel();
        line5Question2 = new javax.swing.JLabel();
        labelAnswer1Question3 = new javax.swing.JLabel();
        labelAnswer2Question3 = new javax.swing.JLabel();
        labelAnswer3Question3 = new javax.swing.JLabel();
        labelAnswer4Question3 = new javax.swing.JLabel();
        userInputQuestion3 = new javax.swing.JTextField();
        label1Question4 = new javax.swing.JLabel();
        label2Question4 = new javax.swing.JLabel();
        panelCodeQuestion4 = new javax.swing.JPanel();
        line1Question4 = new javax.swing.JLabel();
        line2Question4 = new javax.swing.JLabel();
        line3Question4 = new javax.swing.JLabel();
        line4Question4 = new javax.swing.JLabel();
        line5Question3 = new javax.swing.JLabel();
        line6Question2 = new javax.swing.JLabel();
        labelAnswer1Question4 = new javax.swing.JLabel();
        labelAnswer2Question4 = new javax.swing.JLabel();
        labelAnswer3Question4 = new javax.swing.JLabel();
        labelAnswer4Question4 = new javax.swing.JLabel();
        userInputQuestion4 = new javax.swing.JTextField();
        label1Question5 = new javax.swing.JLabel();
        label2Question5 = new javax.swing.JLabel();
        panelCodeQuestion5 = new javax.swing.JPanel();
        line1Question5 = new javax.swing.JLabel();
        line2Question5 = new javax.swing.JLabel();
        line3Question5 = new javax.swing.JLabel();
        line4Question5 = new javax.swing.JLabel();
        line5Question4 = new javax.swing.JLabel();
        line6Question3 = new javax.swing.JLabel();
        line6Question4 = new javax.swing.JLabel();
        labelAnswer1Question5 = new javax.swing.JLabel();
        labelAnswer2Question5 = new javax.swing.JLabel();
        userInputQuestion5 = new javax.swing.JTextField();
        label3Question5 = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        quizScoreLabel = new javax.swing.JLabel();
        quizScorePercentageOutputLabel1 = new javax.swing.JLabel();
        quizScoreAmountIncorrectOutputLabel1 = new javax.swing.JLabel();
        quizScoreAmountCorrectOutputLabel2 = new javax.swing.JLabel();
        textOutput1 = new javax.swing.JLabel();
        textOutput2 = new javax.swing.JLabel();
        textOutput3 = new javax.swing.JLabel();
        textOutput4 = new javax.swing.JLabel();
        textOutput5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(153, 204, 255));

        titleLabel.setFont(new java.awt.Font("Segoe Print", 3, 48)); // NOI18N
        titleLabel.setText("Stepping Through Code");

        pictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.jpeg"))); // NOI18N

        informationBackgroundPanel.setBackground(new java.awt.Color(204, 204, 255));

        quizInstructionsLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        quizInstructionsLabel2.setText("corresponds with (ie. 1 ). When you are done the quiz, click enter & your");

        quizInstructionsLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        quizInstructionsLabel3.setText("quiz score will appear in the bottom right corner.");

        quizInstructionsLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        quizInstructionsLabel1.setText("Answer each question by typing in the number in which your answer");

        javax.swing.GroupLayout informationBackgroundPanelLayout = new javax.swing.GroupLayout(informationBackgroundPanel);
        informationBackgroundPanel.setLayout(informationBackgroundPanelLayout);
        informationBackgroundPanelLayout.setHorizontalGroup(
            informationBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quizInstructionsLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addComponent(quizInstructionsLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quizInstructionsLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        informationBackgroundPanelLayout.setVerticalGroup(
            informationBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizInstructionsLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizInstructionsLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizInstructionsLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label1Question1.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        label1Question1.setText("Question 1: What is the value of num3 ");

        label2Question1.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        label2Question1.setText("after the following code has been executed: ");

        panelCodeQuestion1.setBackground(new java.awt.Color(204, 204, 204));

        line1Question1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line1Question1.setText("        int num1; ");

        line2Question1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line2Question1.setText("        int num2;");

        line3Question1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line3Question1.setText("        int num3;");

        line4Question1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line4Question1.setText("        num1 = 4;");

        line5Question1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line5Question1.setText("        num2 = 10;");

        line6Question1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line6Question1.setText("        num3 = num1 + num2; ");

        javax.swing.GroupLayout panelCodeQuestion1Layout = new javax.swing.GroupLayout(panelCodeQuestion1);
        panelCodeQuestion1.setLayout(panelCodeQuestion1Layout);
        panelCodeQuestion1Layout.setHorizontalGroup(
            panelCodeQuestion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeQuestion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCodeQuestion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line3Question1)
                    .addComponent(line4Question1)
                    .addComponent(line5Question1)
                    .addComponent(line6Question1)
                    .addComponent(line2Question1)
                    .addComponent(line1Question1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCodeQuestion1Layout.setVerticalGroup(
            panelCodeQuestion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeQuestion1Layout.createSequentialGroup()
                .addComponent(line1Question1)
                .addGap(5, 5, 5)
                .addComponent(line2Question1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line3Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(line4Question1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line5Question1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line6Question1))
        );

        labelAnswer1Question1.setText("1) 6");

        labelAnswer2Question1.setText("2) 10");

        labelAnswer3Question1.setText("3) 14");

        labelAnswer4Question1.setText("4) 4");

        label1Question2.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        label1Question2.setText("Question 2: What is the value of value2 ");

        label2Question2.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        label2Question2.setText("after the following code has been executed:");

        panelCodeQuestion2.setBackground(new java.awt.Color(204, 204, 204));

        line1Question2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line1Question2.setText("        int value1; ");

        line2Question2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line2Question2.setText("        int value2; ");

        line3Question2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line3Question2.setText("        value1 = 5; ");

        line4Question2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line4Question2.setText("        value2 = value1 * 8;");

        javax.swing.GroupLayout panelCodeQuestion2Layout = new javax.swing.GroupLayout(panelCodeQuestion2);
        panelCodeQuestion2.setLayout(panelCodeQuestion2Layout);
        panelCodeQuestion2Layout.setHorizontalGroup(
            panelCodeQuestion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeQuestion2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCodeQuestion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line3Question2)
                    .addComponent(line4Question2)
                    .addComponent(line2Question2)
                    .addComponent(line1Question2))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelCodeQuestion2Layout.setVerticalGroup(
            panelCodeQuestion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeQuestion2Layout.createSequentialGroup()
                .addComponent(line1Question2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(line2Question2)
                .addGap(18, 18, 18)
                .addComponent(line3Question2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line4Question2)
                .addContainerGap())
        );

        labelAnswer1Question2.setText("1) 40");

        labelAnswer2Question2.setText("2) 3");

        labelAnswer3Question2.setText("3) 8");

        labelAnswer4Question2.setText("4) -3");

        label1Question3.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        label1Question3.setText("Question 3: What is the value of n3");

        label2Question3.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        label2Question3.setText("after the following code has been executed: ");

        panelCodeQuestion3.setBackground(new java.awt.Color(204, 204, 204));

        line1Question3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line1Question3.setText("        int n1 = 10; ");

        line2Question3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line2Question3.setText("        int n2 = n1 + 5; ");

        line3Question3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line3Question3.setText("        int n3 = n2; ");

        line4Question3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line4Question3.setText("        n1 = n1 * 2; ");

        line5Question2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line5Question2.setText("        n3 = n1 + 10; ");

        javax.swing.GroupLayout panelCodeQuestion3Layout = new javax.swing.GroupLayout(panelCodeQuestion3);
        panelCodeQuestion3.setLayout(panelCodeQuestion3Layout);
        panelCodeQuestion3Layout.setHorizontalGroup(
            panelCodeQuestion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeQuestion3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCodeQuestion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line3Question3)
                    .addComponent(line4Question3)
                    .addComponent(line5Question2)
                    .addComponent(line2Question3)
                    .addComponent(line1Question3))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelCodeQuestion3Layout.setVerticalGroup(
            panelCodeQuestion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeQuestion3Layout.createSequentialGroup()
                .addComponent(line1Question3)
                .addGap(5, 5, 5)
                .addComponent(line2Question3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line3Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(line4Question3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line5Question2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelAnswer1Question3.setText("1) 15");

        labelAnswer2Question3.setText("2) 12");

        labelAnswer3Question3.setText("3) 20");

        labelAnswer4Question3.setText("4) 30");

        label1Question4.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        label1Question4.setText("Question 4: What is the value of val2");

        label2Question4.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        label2Question4.setText("after the following code has been executed: ");

        panelCodeQuestion4.setBackground(new java.awt.Color(204, 204, 204));

        line1Question4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line1Question4.setText("        int val1 = 20; ");

        line2Question4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line2Question4.setText("        int val2 = val1 + 40; ");

        line3Question4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line3Question4.setText("        if (val1 > 20) ");

        line4Question4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line4Question4.setText("        {val1 = val2 + 10;} ");

        line5Question3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line5Question3.setText("        else ");

        line6Question2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line6Question2.setText("        {val2 = val2 - 10;} ");

        javax.swing.GroupLayout panelCodeQuestion4Layout = new javax.swing.GroupLayout(panelCodeQuestion4);
        panelCodeQuestion4.setLayout(panelCodeQuestion4Layout);
        panelCodeQuestion4Layout.setHorizontalGroup(
            panelCodeQuestion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeQuestion4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCodeQuestion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line3Question4)
                    .addComponent(line4Question4)
                    .addComponent(line5Question3)
                    .addComponent(line6Question2)
                    .addComponent(line2Question4)
                    .addComponent(line1Question4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCodeQuestion4Layout.setVerticalGroup(
            panelCodeQuestion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeQuestion4Layout.createSequentialGroup()
                .addComponent(line1Question4)
                .addGap(5, 5, 5)
                .addComponent(line2Question4)
                .addGap(18, 18, 18)
                .addComponent(line3Question4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line4Question4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line5Question3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line6Question2))
        );

        labelAnswer1Question4.setText("1) 50");

        labelAnswer2Question4.setText("2) 70");

        labelAnswer3Question4.setText("3) 60");

        labelAnswer4Question4.setText("4) 20");

        label1Question5.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        label1Question5.setText("Question 5: What would be output to the");

        label2Question5.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        label2Question5.setText(" console after the following code has been ");

        panelCodeQuestion5.setBackground(new java.awt.Color(204, 204, 204));

        line1Question5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line1Question5.setText("        int number1 = 10; ");

        line2Question5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line2Question5.setText("        int number2 = number1 * 5; ");

        line3Question5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line3Question5.setText("        int number3 = number1 + number2; ");

        line4Question5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line4Question5.setText("        if (number3 < number1) ");

        line5Question4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line5Question4.setText("        {System.out.println(\"Computer Science!\");} ");

        line6Question3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line6Question3.setText("        else ");

        line6Question4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        line6Question4.setText("        {System.out.println(\"CS!\");} ");

        javax.swing.GroupLayout panelCodeQuestion5Layout = new javax.swing.GroupLayout(panelCodeQuestion5);
        panelCodeQuestion5.setLayout(panelCodeQuestion5Layout);
        panelCodeQuestion5Layout.setHorizontalGroup(
            panelCodeQuestion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeQuestion5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCodeQuestion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line3Question5)
                    .addComponent(line4Question5)
                    .addComponent(line5Question4)
                    .addComponent(line6Question3)
                    .addComponent(line2Question5)
                    .addComponent(line1Question5)
                    .addComponent(line6Question4)))
        );
        panelCodeQuestion5Layout.setVerticalGroup(
            panelCodeQuestion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeQuestion5Layout.createSequentialGroup()
                .addComponent(line1Question5)
                .addGap(5, 5, 5)
                .addComponent(line2Question5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line3Question5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(line4Question5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line5Question4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line6Question3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line6Question4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelAnswer1Question5.setText("1) CS!");

        labelAnswer2Question5.setText("2) Computer Science!");

        label3Question5.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        label3Question5.setText(" executed: ");

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        quizScoreLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        quizScoreLabel.setText("Quiz Score");

        quizScorePercentageOutputLabel1.setToolTipText("");

        quizScoreAmountIncorrectOutputLabel1.setToolTipText("");

        quizScoreAmountCorrectOutputLabel2.setToolTipText("");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2Question1)
                            .addComponent(label1Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(panelCodeQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAnswer1Question1)
                                    .addComponent(labelAnswer2Question1)
                                    .addComponent(labelAnswer3Question1)
                                    .addComponent(labelAnswer4Question1)
                                    .addComponent(userInputQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(panelCodeQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userInputQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAnswer1Question3)
                                    .addComponent(labelAnswer2Question3)
                                    .addComponent(labelAnswer3Question3)
                                    .addComponent(labelAnswer4Question3)))
                            .addComponent(label2Question3)
                            .addComponent(label1Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPanelLayout.createSequentialGroup()
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(panelCodeQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textOutput2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(userInputQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelAnswer1Question2)
                                            .addComponent(labelAnswer2Question2)
                                            .addComponent(labelAnswer3Question2)
                                            .addComponent(labelAnswer4Question2)))
                                    .addComponent(label2Question2)
                                    .addComponent(label1Question2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addComponent(panelCodeQuestion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelAnswer1Question4)
                                            .addComponent(labelAnswer2Question4)
                                            .addComponent(labelAnswer3Question4)
                                            .addComponent(labelAnswer4Question4)
                                            .addComponent(userInputQuestion4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(label2Question4)
                                    .addComponent(label1Question4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textOutput4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPanelLayout.createSequentialGroup()
                                .addComponent(textOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)
                                .addComponent(textOutput3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2Question5)
                                    .addComponent(label3Question5)
                                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label1Question5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelAnswer2Question5)
                                    .addComponent(labelAnswer1Question5)
                                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                            .addComponent(userInputQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textOutput5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(panelCodeQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(enterButton))
                                .addGap(0, 36, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quizScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(quizScoreAmountIncorrectOutputLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addComponent(quizScoreAmountCorrectOutputLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quizScorePercentageOutputLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(informationBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(informationBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(label1Question5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(label2Question5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(label3Question5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(panelCodeQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAnswer1Question5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAnswer2Question5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userInputQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textOutput5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(enterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quizScoreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quizScoreAmountIncorrectOutputLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quizScoreAmountCorrectOutputLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quizScorePercentageOutputLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(label1Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(label2Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(panelCodeQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addComponent(labelAnswer1Question3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer2Question3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer3Question3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer4Question3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(userInputQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textOutput3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(label1Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(label2Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                        .addComponent(labelAnswer1Question1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer2Question1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer3Question1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer4Question1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(userInputQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(panelCodeQuestion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(label1Question2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(label2Question2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelCodeQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addComponent(labelAnswer1Question2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer2Question2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer3Question2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer4Question2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(userInputQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textOutput2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(label1Question4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(label2Question4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addComponent(labelAnswer1Question4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer2Question4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer3Question4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAnswer4Question4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(userInputQuestion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(panelCodeQuestion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textOutput4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed

              
        //Getting the answer from each question
        double answer1;
        answer1 = Double.parseDouble(userInputQuestion1.getText());
        
        double answer2;
        answer2 = Double.parseDouble(userInputQuestion2.getText());
        
        double answer3;
        answer3 = Double.parseDouble(userInputQuestion3.getText());
        
        double answer4;
        answer4 = Double.parseDouble(userInputQuestion4.getText());
        
        double answer5;
        answer5 = Double.parseDouble(userInputQuestion5.getText());
        
        //calling variables for the amount of correct, incorrect, as well as percentage
        double correct = 0;
        double incorrect = 0;
        double percentage = 0;
        double correctanswr1 = 3;
        double correctanswr2 = 1;
        double correctanswr3 = 4;
        double correctanswr4 = 1;
        double correctanswr5 = 1;
        
        
        
        if(answer1==correctanswr1){
        correct = correct + 1;
        textOutput1.setText("Correct!");
        } 
        else {
         incorrect = incorrect+1;              
        textOutput1.setText("Incorrect!");
        }
        
        if(answer2==correctanswr2){
        correct = correct + 1;
        textOutput2.setText("Correct!");
        } 
        else {
         incorrect = incorrect+1;              
        textOutput2.setText("Incorrect!");
        }
        
        if(answer3==correctanswr3){
        correct = correct + 1;
        textOutput3.setText("Correct!");
        } 
        else {
         incorrect = incorrect+1;              
        textOutput3.setText("Incorrect!");
        }        
        
        if(answer4==correctanswr4){
        correct = correct + 1;
        textOutput4.setText("Correct!");
        } 
        else {
         incorrect = incorrect+1;              
        textOutput4.setText("Incorrect!");
        }        

        if(answer5==correctanswr5){
        correct = correct + 1;
        textOutput5.setText("Correct!");
        } 
        else {
         incorrect = incorrect+1;              
        textOutput5.setText("Incorrect!");
        }        
        
        
        //percentage equations
        percentage = correct/5;
        percentage = percentage*100;
        
        //setiing test score labels
        quizScoreAmountCorrectOutputLabel2.setText(correct + " out of 5 correct");
        quizScoreAmountIncorrectOutputLabel1.setText(incorrect + " out of 5 incorrect");
        quizScorePercentageOutputLabel1.setText("You got " +percentage + "%");
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSummativeProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSummativeProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSummativeProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSummativeProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSummativeProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton enterButton;
    private javax.swing.JPanel informationBackgroundPanel;
    private javax.swing.JLabel label1Question1;
    private javax.swing.JLabel label1Question2;
    private javax.swing.JLabel label1Question3;
    private javax.swing.JLabel label1Question4;
    private javax.swing.JLabel label1Question5;
    private javax.swing.JLabel label2Question1;
    private javax.swing.JLabel label2Question2;
    private javax.swing.JLabel label2Question3;
    private javax.swing.JLabel label2Question4;
    private javax.swing.JLabel label2Question5;
    private javax.swing.JLabel label3Question5;
    private javax.swing.JLabel labelAnswer1Question1;
    private javax.swing.JLabel labelAnswer1Question2;
    private javax.swing.JLabel labelAnswer1Question3;
    private javax.swing.JLabel labelAnswer1Question4;
    private javax.swing.JLabel labelAnswer1Question5;
    private javax.swing.JLabel labelAnswer2Question1;
    private javax.swing.JLabel labelAnswer2Question2;
    private javax.swing.JLabel labelAnswer2Question3;
    private javax.swing.JLabel labelAnswer2Question4;
    private javax.swing.JLabel labelAnswer2Question5;
    private javax.swing.JLabel labelAnswer3Question1;
    private javax.swing.JLabel labelAnswer3Question2;
    private javax.swing.JLabel labelAnswer3Question3;
    private javax.swing.JLabel labelAnswer3Question4;
    private javax.swing.JLabel labelAnswer4Question1;
    private javax.swing.JLabel labelAnswer4Question2;
    private javax.swing.JLabel labelAnswer4Question3;
    private javax.swing.JLabel labelAnswer4Question4;
    private javax.swing.JLabel line1Question1;
    private javax.swing.JLabel line1Question2;
    private javax.swing.JLabel line1Question3;
    private javax.swing.JLabel line1Question4;
    private javax.swing.JLabel line1Question5;
    private javax.swing.JLabel line2Question1;
    private javax.swing.JLabel line2Question2;
    private javax.swing.JLabel line2Question3;
    private javax.swing.JLabel line2Question4;
    private javax.swing.JLabel line2Question5;
    private javax.swing.JLabel line3Question1;
    private javax.swing.JLabel line3Question2;
    private javax.swing.JLabel line3Question3;
    private javax.swing.JLabel line3Question4;
    private javax.swing.JLabel line3Question5;
    private javax.swing.JLabel line4Question1;
    private javax.swing.JLabel line4Question2;
    private javax.swing.JLabel line4Question3;
    private javax.swing.JLabel line4Question4;
    private javax.swing.JLabel line4Question5;
    private javax.swing.JLabel line5Question1;
    private javax.swing.JLabel line5Question2;
    private javax.swing.JLabel line5Question3;
    private javax.swing.JLabel line5Question4;
    private javax.swing.JLabel line6Question1;
    private javax.swing.JLabel line6Question2;
    private javax.swing.JLabel line6Question3;
    private javax.swing.JLabel line6Question4;
    private javax.swing.JPanel panelCodeQuestion1;
    private javax.swing.JPanel panelCodeQuestion2;
    private javax.swing.JPanel panelCodeQuestion3;
    private javax.swing.JPanel panelCodeQuestion4;
    private javax.swing.JPanel panelCodeQuestion5;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JLabel quizInstructionsLabel1;
    private javax.swing.JLabel quizInstructionsLabel2;
    private javax.swing.JLabel quizInstructionsLabel3;
    private javax.swing.JLabel quizScoreAmountCorrectOutputLabel2;
    private javax.swing.JLabel quizScoreAmountIncorrectOutputLabel1;
    private javax.swing.JLabel quizScoreLabel;
    private javax.swing.JLabel quizScorePercentageOutputLabel1;
    private javax.swing.JLabel textOutput1;
    private javax.swing.JLabel textOutput2;
    private javax.swing.JLabel textOutput3;
    private javax.swing.JLabel textOutput4;
    private javax.swing.JLabel textOutput5;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField userInputQuestion1;
    private javax.swing.JTextField userInputQuestion2;
    private javax.swing.JTextField userInputQuestion3;
    private javax.swing.JTextField userInputQuestion4;
    private javax.swing.JTextField userInputQuestion5;
    // End of variables declaration//GEN-END:variables
}
