/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kaiat
 */
public class FormMakingPurchases extends javax.swing.JFrame {

    /**
     * Creates new form FormMakingPurchases
     */
    public FormMakingPurchases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        pictureLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        infoLabel1 = new javax.swing.JLabel();
        infoLabel2 = new javax.swing.JLabel();
        appleMiniPie = new javax.swing.JLabel();
        blueberryMiniPie = new javax.swing.JLabel();
        pumpkinMiniPie = new javax.swing.JLabel();
        lemonMiniPie = new javax.swing.JLabel();
        applePieInput = new javax.swing.JTextField();
        blueberryPieInput = new javax.swing.JTextField();
        pumpkinPieInput = new javax.swing.JTextField();
        lemonPieInput = new javax.swing.JTextField();
        doneButton = new javax.swing.JButton();
        taxesLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        grandtotalLabel = new javax.swing.JLabel();
        taxesOutput = new javax.swing.JLabel();
        subtotalOutput = new javax.swing.JLabel();
        grandtotalOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(153, 153, 255));

        pictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pies.jpg"))); // NOI18N

        titleLabel.setFont(new java.awt.Font("Segoe Print", 3, 40)); // NOI18N
        titleLabel.setText("HomeMade Mini Pies");

        infoLabel1.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        infoLabel1.setText("Enter the amount of each mini pie you would like ");

        infoLabel2.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        infoLabel2.setText("purchase, then press done.");

        appleMiniPie.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        appleMiniPie.setText("Apple Mini Pie ($4.99):");

        blueberryMiniPie.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        blueberryMiniPie.setText("Blueberry Mini Pie ($6.99):");

        pumpkinMiniPie.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        pumpkinMiniPie.setText("Pumpkin Mini Pie ($5.99):");

        lemonMiniPie.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        lemonMiniPie.setText("Lemon Mini Pie ($3.99):");

        applePieInput.setFont(new java.awt.Font("Gabriola", 0, 26)); // NOI18N
        applePieInput.setText(" 0 ");
        applePieInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applePieInputActionPerformed(evt);
            }
        });

        blueberryPieInput.setFont(new java.awt.Font("Gabriola", 0, 26)); // NOI18N
        blueberryPieInput.setText(" 0 ");
        blueberryPieInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueberryPieInputActionPerformed(evt);
            }
        });

        pumpkinPieInput.setFont(new java.awt.Font("Gabriola", 0, 26)); // NOI18N
        pumpkinPieInput.setText(" 0 ");
        pumpkinPieInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumpkinPieInputActionPerformed(evt);
            }
        });

        lemonPieInput.setFont(new java.awt.Font("Gabriola", 0, 26)); // NOI18N
        lemonPieInput.setText(" 0 ");
        lemonPieInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonPieInputActionPerformed(evt);
            }
        });

        doneButton.setBackground(new java.awt.Color(0, 255, 255));
        doneButton.setFont(new java.awt.Font("Gabriola", 0, 26)); // NOI18N
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        taxesLabel.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        taxesLabel.setText("Taxes (13%):");

        subtotalLabel.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        subtotalLabel.setText("Subtotal:");

        grandtotalLabel.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        grandtotalLabel.setText("Grandtotal:");

        taxesOutput.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        taxesOutput.setText("$0.00");

        subtotalOutput.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        subtotalOutput.setText("$0.00");

        grandtotalOutput.setFont(new java.awt.Font("Gabriola", 2, 26)); // NOI18N
        grandtotalOutput.setText("$0.00");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoLabel2)
                            .addComponent(infoLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(blueberryMiniPie)
                    .addComponent(appleMiniPie)
                    .addComponent(pumpkinMiniPie)
                    .addComponent(lemonMiniPie))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doneButton)
                    .addComponent(lemonPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(applePieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueberryPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pumpkinPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxesLabel)
                            .addComponent(subtotalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(grandtotalLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxesOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grandtotalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(infoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(infoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appleMiniPie)
                    .addComponent(applePieInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxesLabel)
                    .addComponent(taxesOutput))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueberryMiniPie)
                    .addComponent(blueberryPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalLabel)
                    .addComponent(subtotalOutput))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pumpkinMiniPie)
                    .addComponent(pumpkinPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grandtotalLabel)
                    .addComponent(grandtotalOutput))
                .addGap(14, 14, 14)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lemonPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lemonMiniPie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applePieInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applePieInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applePieInputActionPerformed

    private void blueberryPieInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueberryPieInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueberryPieInputActionPerformed

    private void pumpkinPieInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumpkinPieInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pumpkinPieInputActionPerformed

    private void lemonPieInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonPieInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lemonPieInputActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // cost of each
        double appleMiniPie = 4.99;
        double blueberryMiniPie = 6.99;
        double pumpkinMiniPie = 9.99;
        double lemonMiniPie = 3.99;
        
        //amount of each
        double apple;
        apple = Double.parseDouble(applePieInput.getText());
        double blueberry;
        blueberry = Double.parseDouble(blueberryPieInput.getText());
        double pumpkin;
        pumpkin = Double.parseDouble(pumpkinPieInput.getText());
        double lemon;
        lemon = Double.parseDouble(lemonPieInput.getText());

        double appleTotalPrice;
        appleTotalPrice = (apple*appleMiniPie);
        double blueberryTotalPrice;
        blueberryTotalPrice = (blueberry*blueberryMiniPie);
        double pumkinTotalPrice;
        pumkinTotalPrice = (pumpkin*pumpkinMiniPie);
        double lemonTotalPrice;
        lemonTotalPrice = (lemon*lemonMiniPie);
        
        double total;
        total = appleTotalPrice+blueberryTotalPrice+pumkinTotalPrice+lemonTotalPrice;
        
        double subtotal;
        subtotal = total;
        subtotal = subtotal*100;
        subtotal = Math.round(subtotal);
        subtotal = subtotal/100;
        subtotalOutput.setText("$"+subtotal);
        
        double taxes;
        taxes = total*0.13;
        taxes = taxes*100;
        taxes = Math.round(taxes);
        taxes = taxes/100;
        taxesOutput.setText("$"+taxes);
        
        double grandtotal;
        grandtotal = total+taxes;
        grandtotal = grandtotal*100;
        grandtotal = Math.round(grandtotal);
        grandtotal = grandtotal/100;
        grandtotalOutput.setText("$"+grandtotal);
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMakingPurchases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appleMiniPie;
    private javax.swing.JTextField applePieInput;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel blueberryMiniPie;
    private javax.swing.JTextField blueberryPieInput;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel grandtotalLabel;
    private javax.swing.JLabel grandtotalOutput;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel infoLabel2;
    private javax.swing.JLabel lemonMiniPie;
    private javax.swing.JTextField lemonPieInput;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JLabel pumpkinMiniPie;
    private javax.swing.JTextField pumpkinPieInput;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel subtotalOutput;
    private javax.swing.JLabel taxesLabel;
    private javax.swing.JLabel taxesOutput;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
